name: salon
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  flutter_screenutil: ^5.7.0
  go_router: ^7.1.1
  dio: ^5.1.2
  shared_preferences: ^2.1.1
  flutter_svg: ^1.1.6
  event_bus: ^2.0.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  logger: ^1.3.0
  cached_network_image: ^3.2.3
  connectivity_plus: ^3.0.6
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  injectable: ^2.1.1
  easy_localization: ^3.0.2
  device_info_plus: ^8.2.2
  get_it: ^7.6.0
  package_info_plus: ^3.1.2
  shimmer: ^3.0.0
  expandable_text: ^2.3.0
  infinite_scroll_pagination: ^3.2.0
  intl:
  lottie: ^1.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  freezed: ^2.3.2
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  json_serializable: ^6.6.0
  injectable_generator:
  flutter_gen_runner: ^5.3.1
  flutter_launcher_icons:
  change_app_package_name: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/animations/
    - assets/i18n/

  fonts:
    - family: Yekan
      fonts:
        - asset: assets/fonts/iran_yekan_regular.ttf
          weight: 300
        - asset: assets/fonts/iran_yekan_medium.ttf
          weight: 500
        - asset: assets/fonts/iran_yekan_bold.ttf
          weight: 700
        - asset: assets/fonts/iran_yekan_bold_button.ttf
          weight: 800

flutter_gen:
  output: lib/gen/
  line_length: 80
  integrations:
    flutter_svg: true
    lottie: true
